[platformio]
default_envs = start_station, finish_station
src_dir = .

[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps =
  jgromes/RadioLib@^7.1.2
  bblanchon/ArduinoJson@^7.4.2
  olikraus/U8g2@^2.36.5
build_flags =
  -D LORA_FREQUENCY_MHZ=868.0
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -I common
  -I common/protocol
  -I common/time
  -I common/display
  -I common/hardware

[env:start_station]
build_flags =
  ${env.build_flags}
  -D START_STATION
  -I start-station/src
build_src_filter =
  +<common/**/*.cpp>
  +<start-station/src/**/*.cpp>
  -<finish-station/**>
board_build.filesystem = littlefs
data_dir = start-station/data

[env:finish_station]
build_flags =
  ${env.build_flags}
  -D FINISH_STATION
  -I finish-station/src
build_src_filter =
  +<common/**/*.cpp>
  +<finish-station/src/**/*.cpp>
  -<start-station/**>
board_build.filesystem = littlefs
