#pragma once

#include "FirmwareConfig.h"

#ifndef ENABLE_LORA_TIME_SYNC
#define ENABLE_LORA_TIME_SYNC 0
#endif

#ifndef LORA_RX_POLL_TIMEOUT_MS
#define LORA_RX_POLL_TIMEOUT_MS 0
#endif

#ifndef LORA_MAX_POLL_DURATION_WARN_MS
#define LORA_MAX_POLL_DURATION_WARN_MS 20
#endif

#ifndef LORA_MAX_TX_DURATION_WARN_MS
#define LORA_MAX_TX_DURATION_WARN_MS 300
#endif

#ifndef LORA_BANDWIDTH_KHZ
#define LORA_BANDWIDTH_KHZ 125.0
#endif

#ifndef LORA_SPREADING_FACTOR
#define LORA_SPREADING_FACTOR 10
#endif

#ifndef LORA_CODING_RATE
#define LORA_CODING_RATE 5
#endif

#ifndef LORA_TX_POWER_DBM
#define LORA_TX_POWER_DBM 14
#endif

#ifndef FINISH_STATUS_ENABLED_CFG
#define FINISH_STATUS_ENABLED_CFG 1
#endif

#ifndef FINISH_HELLO_ENABLED_CFG
#define FINISH_HELLO_ENABLED_CFG 0
#endif

#ifndef START_HELLO_ENABLED_CFG
#define START_HELLO_ENABLED_CFG 0
#endif

#ifndef HELLO_ACK_ENABLED_CFG
#define HELLO_ACK_ENABLED_CFG 0
#endif

#ifndef FINISH_STATUS_INTERVAL_MS_CFG
#define FINISH_STATUS_INTERVAL_MS_CFG 15000UL
#endif

#ifndef FINISH_DISCOVERY_INTERVAL_MS_CFG
#define FINISH_DISCOVERY_INTERVAL_MS_CFG 120000UL
#endif

#ifndef START_DISCOVERY_INTERVAL_MS_CFG
#define START_DISCOVERY_INTERVAL_MS_CFG 120000UL
#endif

#ifndef REPEATER_RELAY_STATUS_CFG
#define REPEATER_RELAY_STATUS_CFG 0
#endif

#ifndef REPEATER_RELAY_HELLO_CFG
#define REPEATER_RELAY_HELLO_CFG 0
#endif

#ifndef MINIMAL_LORA_DEBUG_MODE_CFG
#define MINIMAL_LORA_DEBUG_MODE_CFG 0
#endif

#if MINIMAL_LORA_DEBUG_MODE_CFG
#undef FINISH_STATUS_INTERVAL_MS_CFG
#define FINISH_STATUS_INTERVAL_MS_CFG 30000UL
#endif
