#pragma once

#define ENDURO_TIMER_FIRMWARE_VERSION "0.31"

#if defined(START_STATION)
  #define ENDURO_TIMER_FIRMWARE_ROLE "StartStation"
  #define ENDURO_TIMER_FIRMWARE_ROLE_SHORT "START"
#elif defined(FINISH_STATION)
  #define ENDURO_TIMER_FIRMWARE_ROLE "FinishStation"
  #define ENDURO_TIMER_FIRMWARE_ROLE_SHORT "FINISH"
#elif defined(REPEATER_STATION)
  #define ENDURO_TIMER_FIRMWARE_ROLE "RepeaterStation"
  #define ENDURO_TIMER_FIRMWARE_ROLE_SHORT "REPEATER"
#else
  #define ENDURO_TIMER_FIRMWARE_ROLE "Unknown"
  #define ENDURO_TIMER_FIRMWARE_ROLE_SHORT "UNKNOWN"
#endif

#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION ENDURO_TIMER_FIRMWARE_VERSION
#endif

#ifndef FIRMWARE_ROLE
#define FIRMWARE_ROLE ENDURO_TIMER_FIRMWARE_ROLE
#endif
